package domain;

public enum Genere {
	ANIPARO, CYBERPUNK, KODOMO, SHONEN, SEINEN, GEKIGA, GORE, JOSEI,
	SHOJO, MECHA ,MEITANTEI,ROMAKONE,SPOKON,SURIAA,FANTASCIENZA,
	
	WESTERN, POLIZIESCO, HORROR, AVVENTURA, FANTASY, COMICO, SATIRA,
	PULP_E_TRASH, SPORTIVO, ROMANTICO;

}
